FROM node:22-alpine AS builder

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY . .

RUN pnpm install --frozen-lockfile 
RUN pnpm --filter bot... build
RUN pnpm deploy --filter bot --prod /out



FROM node:22-alpine AS runner
RUN apk add --no-cache ffmpeg python3 curl py3-pip deno && \
    curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && \
    chmod a+rx /usr/local/bin/yt-dlp

WORKDIR /app

COPY --from=builder /out .
USER node
CMD ["node", "dist/main.js"]