FROM node:22-alpine AS builder
RUN corepack enable

WORKDIR /app

COPY . .

RUN pnpm install --frozen-lockfile 
RUN pnpm --filter bot... build
RUN pnpm deploy --filter bot --prod --legacy /out



FROM node:22-alpine AS runner
RUN apk add --no-cache ffmpeg python3 curl py3-pip deno 
RUN pip install --no-cache-dir --upgrade yt-dlp --break-system-packages

WORKDIR /app

COPY --from=builder /out .
USER node
CMD ["node", "dist/main.js"]